# $Id: Makefile.win,v 1.1 2006/12/04 16:07:55 mascarenhas Exp $

LUA_DIR= c:/lua51/lua
CGILUA_DIR= $(LUA_DIR)/cgilua
CONFIG_FILE= config.lua

install:
	mkdir -p $(CGILUA_DIR)
	copy src/cgilua/*.lua $(CGILUA_DIR)

clean:
