# $Id: Makefile.win,v 1.3 2006/12/20 17:54:24 carregal Exp $

LUA_DIR= c:\lua51\lua
CGILUA_DIR= $(LUA_DIR)\cgilua
CONFIG_FILE= config.lua

clean:

install:
	IF NOT EXIST $(CGILUA_DIR) mkdir $(CGILUA_DIR)
	copy src\cgilua\*.lua $(CGILUA_DIR)

