# $Id: Makefile.win,v 1.4 2007/03/15 21:27:58 carregal Exp $

LUA_DIR= c:\lua5.1\lua
CGILUA_DIR= $(LUA_DIR)\cgilua
CONFIG_FILE= config.lua

clean:

install:
	IF NOT EXIST $(CGILUA_DIR) mkdir $(CGILUA_DIR)
	copy src\cgilua\*.lua $(CGILUA_DIR)

